default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: franklin

test:
  <<: *default
  database: franklin_test

production:
  <<: *default
  database: franklin
